import { model, Schema } from "mongoose";

const sentinelOneAgentSchema = Schema(
  {
    company_id: String,
    accountId: String,
    accountName: String,
    activeDirectory: [Object],
    activeThreats: Number,
    agentVersion: String,
    allowRemoteShell: Boolean,
    appsVulnerabilityStatus: String,
    cloudProviders: Object,
    computerName: String,
    consoleMigrationStatus: String,
    coreCount: Number,
    cpuCount: Number,
    cpuId: String,
    createdAtOnSource: Date,
    detectionState: String,
    domain: String,
    encryptedApplications: Boolean,
    externalId: String,
    externalIp: String,
    firewallEnabled: Boolean,
    firstFullModeTime: String,
    groupId: String,
    groupIp: String,
    groupName: String,
    id: String,
    inRemoteShellSession: Boolean,
    infected: Boolean,
    installerType: String,
    isActive: Boolean,
    isDecommissioned: Boolean,
    isPendingUninstall: Boolean,
    isUninstalled: Boolean,
    isUpToDate: Boolean,
    lastActiveDate: String,
    lastIpToMgmt: String,
    lastLoggedInUserName: String,
    licenseKey: String,
    locationEnabled: Boolean,
    locationType: String,
    locations: Array,
    machineType: String,
    mitigationMode: String,
    mitigationModeSuspicious: String,
    modelName: String,
    networkInterfaces: Array,
    networkQuarantineEnabled: Boolean,
    networkStatus: String,
    operationalState: String,
    operationalStateExpiration: String,
    osArch: String,
    osName: String,
    osRevision: String,
    osStartTime: Date,
    osType: String,
    osUsername: String,
    rangerStatus: String,
    rangerVersion: String,
    registeredAt: Date,
    remoteProfilingState: String,
    remoteProfilingStateExpiration: String,
    scanAbortedAt: Date,
    scanFinishedAt: String,
    scanStartedAt: Date,
    scanStatus: String,
    serialNumber: String,
    siteId: String,
    siteName: String,
    storageName: String,
    storageType: String,
    tags: [Object],
    threatRebootRequired: Boolean,
    totalMemory: Number,
    updatedAt: Date,
    userActionsNeeded: Array,
    uuid: String,
  },
  {
    timestamps: true,
  }
);

const sentinelOneAgentModel = model(
  "sentinelone_agent",
  sentinelOneAgentSchema
);
export default sentinelOneAgentModel;
