import mongoose, { model, Schema } from "mongoose"

const microsoftDevicesSchema = Schema(
  {
    id: String,
    company_id: String,
    userId: String,
    deviceName: String,
    managedDeviceOwnerType: String,
    enrolledDateTime: Date,
    lastSyncDateTime: Date,
    operatingSystem: String,
    complianceState: String,
    jailBroken: String,
    managementAgent: String,
    osVersion: String,
    easActivated: Boolean,
    easDeviceId: String,
    easActivationDateTime: Date,
    azureADRegistered: Boolean,
    deviceEnrollmentType: String,
    activationLockBypassCode: String,
    emailAddress: String,
    azureADDeviceId: String,
    deviceRegistrationState: String,
    deviceCategoryDisplayName: String,
    isSupervised: Boolean,
    exchangeLastSuccessfulSyncDateTime: Date,
    exchangeAccessState: String,
    exchangeAccessStateReason: String,
    remoteAssistanceSessionUrl: String,
    remoteAssistanceSessionErrorDetails: String,
    isEncrypted: Boolean,
    model: String,
    manufacturer: String,
    imei: String,
    complianceGracePeriodExpirationDateTime: Date,
    serialNumber: String,
    phoneNumber: String,
    androidSecurityPatchLevel: String,
    userDisplayName: String,
    configurationManagerClientEnabledFeatures: String,
    wiFiMacAddress: String,
    deviceHealthAttestationState: String,
    subscriberCarrier: String,
    meid: String,
    totalStorageSpaceInBytes: Number,
    freeStorageSpaceInBytes: Number,
    managedDeviceName: String,
    partnerReportedThreatState: String,
    requireUserEnrollmentApproval: String,
    managementCertificateExpirationDate: Date,
    iccid: String,
    udid: String,
    notes: String,
    ethernetMacAddress: String,
    physicalMemoryInBytes: Number,
    deviceActionResults: [],
  },
  {
    timestamps: true,
  }
)

const microsoftDevicesModel = model(
  "microsoft_user_devices",
  microsoftDevicesSchema
)
export default microsoftDevicesModel
