export const permissionSlug = {
    ADMINISTRATION: 'administration',
    RISK_VIEW:"risk_view",
    RESILIENCE:"resilience",
    DASHBOARD:"dashboard",
    HIVE:"hive",
    PRIVILAGE_ACCESS:"privilage_access",
    COMPLIANCE:"compliance",
    EVENT_LOGS:"event_logs",
    PROFILE:"profile",
    ADMINISTRATION_INTEGRATION:"administration_intigration",
    ADMINISTRATION_INTEGRATION_CLOUD:"administration_intigration_cloud",
    ADMINISTRATION_INTEGRATION_NETWORK:"administration_intigration_network",
    ADMINISTRATION_INTEGRATION_ENDPOINT:"administration_intigration_endpoint",
    ADMINISTRATION_INTEGRATION_MAIL:"administration_intigration_mail",
    ADMINISTRATION_INTEGRATION_BACKUP:"administration_intigration_backup",
    ADMINISTRATION_INTEGRATION_PATCHING:"administration_intigration_patching",
    ADMINISTRATION_INTEGRATION_SECURITY_AWARENESS: "administration_intigration_security_awareness",
    ADMINISTRATION_INTEGRATION_MICROSOFT: "administration_intigration_microsoft",
    ADMINISTRATION_USER_MANAGEMENT:"administration_user_management",
    ADMINISTRATION_USER_MANAGEMENT_CURRENT_USER:"administration_user_management_current_user",
    ADMINISTRATION_USER_MANAGEMENT_PENDING_USER:"administration_user_management_pending_user",
    ADMINISTRATION_USER_MANAGEMENT_INVITE_USER:"administration_user_management_invite_user",
    RISK_VIEW_OVERVIEW: "risk_view_overview",
    RISK_VIEW_APPLICATION: "risk_view_application",
    RISK_VIEW_HUMAN_FACTOR: "risk_view_human_factor",
    RISK_VIEW_BUSINESS_RISK: "risk_view_business_risk",
    RESILIENCE_ALL_ASSETS: "resilience_all_assets",
    RESILIENCE_ALL_ASSETS_DETAIL_VIEW: "resilience_all_assets_detail_view",
    RESILIENCE_ENDPOINTS: "resilience_endpoints",
    RESILIENCE_ENDPOINTS_ALL_ENDPOINTS: "resilience_endpoints_all_endpoints",
    RESILIENCE_ENDPOINTS_ALL_ENDPOINTS_OVERVIEW: "resilience_endpoints_all_endpoints_overview",
    RESILIENCE_ENDPOINTS_ALL_ENDPOINTS_DETECTIONS: "resilience_endpoints_all_endpoints_detections",
    RESILIENCE_ENDPOINTS_ALL_ENDPOINTS_SUSPICIOUS_ACTIVITY: "resilience_endpoints_all_endpoints_suspicious_activity",
    RESILIENCE_ENDPOINTS_ALL_ENDPOINTS_REMEDIATION_REQUIRED:"resilience_endpoints_all_endpoints_remediation_required",
    RESILIENCE_ENDPOINTS_ALL_ENDPOINTS_QUARANTINE:"resilience_endpoints_all_endpoints_quarantines",
    RESILIENCE_ENDPOINTS_ALL_ENDPOINTS_EVENTS:"resilience_endpoints_all_endpoints_events",

    RESILIENCE_ENDPOINTS_POLICIES: "resilience_endpoints_policies",
    RESILIENCE_ENDPOINTS_GROUPS: "resilience_endpoints_groups",
    RESILIENCE_PATCHING: "resilience_patching",
    RESILIENCE_PATCHING_OVERVIEW: "resilience_patching_overview",
    RESILIENCE_PATCHING_DEVICES: "resilience_patching_devices",
    RESILIENCE_PATCHING_POLICIES: "resilience_patching_policies",
    RESILIENCE_PATCHING_GROUPS: "resilience_patching_groups",
    RESILIENCE_PATCHING_DEVICES_VIEW_INFO: "resilience_patching_devices_view_info",
    RESILIENCE_PATCHING_DEVICES_VIEW_SOFTWARES: "resilience_patching_devices_view_softwares",
    RESILIENCE_LIFECYCLE: "resilience_lifecycle",
    RESILIENCE_BACKUP: "resilience_backup",
    RESILIENCE_SOFTWARES: "resilience_softwares",
    RESILIENCE_CVES: "resilience_cves",
    RESILIENCE_OVERVIEW: "resilience_overview",
    PRIVILAGE_ACCESS_SECRET: "privilege_access_secret",

    PARTNER_DASHBOARD: "partner_dashboard",
    PARTNER_ADMINISTRATION: "partner_administration",
    PARTNER_MY_HIVE: "partner_my_hive",
    PARTNER_ONBOARD_CLIENT: "partner_onboard_client",
    PARTNER_PROFILE: "partner_profile",

    PARTNER_DASHBOARD_MANAGE_COMPANY: "partner_dashboard_manage_company",
    PARTNER_DASHBOARD_COMPANY_OVERVIEW: "partner_dashboard_company_overview",
    PARTNER_DASHBOARD_COMPANY_ACTIVITY_LOG: "partner_dashboard_company_activity_log",
    PARTNER_DASHBOARD_COMPANY_USER_MANAGEMENT: "partner_dashboard_company_user_management",
    PARTNER_DASHBOARD_COMPANY_LOGIN_TO_COMPANY: "partner_dashboard_company_login_to_company",
    PARTNER_DASHBOARD_COMPANY_USER_MANAGEMENT_CURRENT_USERS: "partner_dashboard_company_user_management_current_users",
    PARTNER_DASHBOARD_COMPANY_USER_MANAGEMENT_PENDING_USERS: "partner_dashboard_company_user_management_pending_users",
    PARTNER_DASHBOARD_COMPANY_USER_MANAGEMENT_INVITED_USERS: "partner_dashboard_company_user_management_invited_users",

    PARTNER_ADMINISTRATION_USER_MANAGEMENT: "partner_administration_user_management",
    PARTNER_ADMINISTRATION_USER_MANAGEMENT_CURRENT_USERS: "partner_administration_user_management_current_users",
    PARTNER_ADMINISTRATION_USER_MANAGEMENT_PENDING_USERS: "partner_administration_user_management_pending_users",
    PARTNER_ADMINISTRATION_USER_MANAGEMENT_INVITED_USERS: "partner_administration_user_management_invited_users",

    PARTNER_ADMINISTRATION_COMPANY_MANAGEMENT: "partner_administration_company_management",
    PARTNER_ADMINISTRATION_COMPANY_MANAGEMENT_INVITED_COMPANIES: "partner_administration_company_management_invited_companies",

    RISK_VIEW_SCORE_MANAGEMENT: "risk_view_score_management",
    RISK_VIEW_SCORE_MANAGEMENT_PRIVILEGE_ACCESS: "privilege_access_score_management",
    RISK_VIEW_SCORE_MANAGEMENT_ASSETS: "assets_score_management",
    RISK_VIEW_SCORE_MANAGEMENT_APPLICATION: "application_score_management",
    RISK_VIEW_SCORE_MANAGEMENT_HUMANS: "humans_score_management",

    RISK_VIEW_RISK_COST: "risk_view_risk_cost",
    RISK_VIEW_RISK_COST_COST_FACTORS: "risk_view_risk_cost_cost_factors",
    RISK_VIEW_RISK_COST_COST_FACTOR_ATTRIBUTES: "risk_view_risk_cost_cost_factor_attributes",
    RISK_VIEW_RISK_COST_DOWNTIME_PROBABILITY: "risk_view_risk_cost_downtime_probability",
    RISK_VIEW_RISK_COST_PRIORITY: "risk_view_risk_cost_priority",
    RISK_VIEW_RISK_TOLERANCE: "risk_view_risk_tolerance",
    RISK_VIEW_RISK_TOLERANCE_TOLERANCES: "risk_view_risk_tolerance_tolerances",
    RISK_VIEW_RISK_TOLERANCE_PRIORITY: "risk_view_risk_tolerance_priority",

    SUPER_ADMIN_CUSTOMERS: "super_admin_customers",
    SUPER_ADMIN_PARTNERS: "super_admin_partners",
    SUPER_ADMIN_ONBOARD_CLIENT: "super_admin_onboard_client",
    SUPER_ADMIN_PROFILE: "super_admin_profile",

    SUPER_ADMIN_CUSTOMER_MANAGE_COMPANY: "super_admin_customer_manage_company",
    SUPER_ADMIN_CUSTOMER_COMPANY_OVERVIEW: "super_admin_customer_company_overview",
    SUPER_ADMIN_CUSTOMER_COMPANY_ACTIVITY_LOG: "super_admin_customer_company_activity_log",
    SUPER_ADMIN_CUSTOMER_COMPANY_USER_MANAGEMENT: "super_admin_customer_company_user_management",
    SUPER_ADMIN_CUSTOMER_COMPANY_LOGIN_TO_COMPANY: "super_admin_customer_company_login_to_company",
    SUPER_ADMIN_CUSTOMER_COMPANY_USER_MANAGEMENT_CURRENT_USERS: "super_admin_customer_company_user_management_current_users",
    SUPER_ADMIN_CUSTOMER_COMPANY_USER_MANAGEMENT_PENDING_USERS: "super_admin_customer_company_user_management_pending_users",
    SUPER_ADMIN_CUSTOMER_COMPANY_USER_MANAGEMENT_INVITED_USERS: "super_admin_customer_company_user_management_invited_users",

    SUPER_ADMIN_PARTNERS_CURRENT_PARTNERS: "super_admin_partners_current_partners",
    SUPER_ADMIN_PARTNERS_INVITED_PARTNERS: "super_admin_partners_invited_partners",
    SUPER_ADMIN_PARTNERS_INVITE_PARTNER: "super_admin_partners_invite_partner",
}